### ISSUE TITLE
spring.jpa.hibernate.naming.physical-strategy 配置失效

### ISSUE THREAD

**Issue by calvinhbj** [wanghuidong2189/springboottest#1]
如order实体的属性如: createTime 数据库字段为 create_time时，在解析sql时会出现异常，请教如何解决？尝试加入如下代码也解决不了：
    	
    	LocalContainerEntityManagerFactoryBean emf = builder
                .dataSource(secondDataSource())
                .packages("com.kestrel.se")
                .persistenceUnit("secondDs").properties(mproperties)
                .build();
    	
    	Properties properties = new Properties();
    	//spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        properties.setProperty("spring.jpa.hibernate.naming.physical-strategy", "org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy");
        emf.setJpaProperties(properties);

**Comment by hdwang123** [comment]
77.6 Configure Hibernate Naming Strategy
Spring Boot provides a consistent naming strategy regardless of the Hibernate generation that you are using. If you are using Hibernate 4, you can customize it using spring.jpa.hibernate.naming.strategy; Hibernate 5 defines a Physical and Implicit naming strategies.

Spring Boot configures SpringPhysicalNamingStrategy by default. This implementation provides the same table structure as Hibernate 4: all dots are replaced by underscores and camel cases are replaced by underscores as well. By default, all table names are generated in lower case but it is possible to override that flag if your schema requires it.

Concretely, a TelephoneNumber entity will be mapped to the telephone_number table.

If you’d rather use Hibernate 5’s default instead, set the following property:

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
See HibernateJpaAutoConfiguration and JpaBaseConfiguration for more details.

这个是官网的文档，按照它说的，默认就是该策略了。你看看你的配置是否对。一个数据库配置在一个配置类中，注意dao路径、entity路径等。

**Comment by hdwang123** [comment]
找到原因了，需要指明JpaProperties。例如：
 public LocalContainerEntityManagerFactoryBean commonEntityManagerFactory(
            EntityManagerFactoryBuilder builder) {
        return builder
                .dataSource(commonDataSource())
                .packages("com.hzxc.wegame.entity.common")
                .persistenceUnit("commonDs")
                .properties(new JpaProperties().getHibernateProperties(commonDataSource()))
                .build();
    }
